[package]
name = "pitch-corrector"
version = "0.1.0"
authors = ["Walter Smuts <wssmts@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4.0"
clap = { version = "3.1", features = ["derive"] }
